List = {
   {name = 'SPR', desc = '', atk = 0, blk = 0},
   {name = 'SWRD', desc = '', atk = 0, blk = 0},
   {name = 'AXE ', desc = '', atk = 0, blk = 0},
   {name = 'SHLD', desc = '', atk = 0, blk = 0},
   {name = 'HP', desc = '', atk = 0, blk = 0},
   {name = 'MANA', desc = '', atk = 0, blk = 0},
   {name = '', desc = '', atk = 0, blk = 0},
   {name = '', desc = '', atk = 0, blk = 0},
   {name = '', desc = '', atk = 0, blk = 0},
   {name = '', desc = '', atk = 0, blk = 0},
   {name = '', desc = '', atk = 0, blk = 0},
   {name = '', desc = '', atk = 0, blk = 0},
   {name = '', desc = '', atk = 0, blk = 0},
   {name = '', desc = '', atk = 0, blk = 0},
   {name = '', desc = '', atk = 0, blk = 0},
   {name = '', desc = '', atk = 0, blk = 0},
   {name = '', desc = '', atk = 0, blk = 0},
   {name = '', desc = '', atk = 0, blk = 0},
   {name = '', desc = '', atk = 0, blk = 0},
   {name = '', desc = '', atk = 0, blk = 0},
}